// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BanLiveUserReducer from "../ban_live_user_reducer";
import BoostLiveReducer from "../boost_live_reducer";
import CreateUserProfileReducer from "../create_user_profile_reducer";
import EndLiveReducer from "../end_live_reducer";
import GrantAdminCurrencyReducer from "../grant_admin_currency_reducer";
import MarkConversationReadReducer from "../mark_conversation_read_reducer";
import RemoveFriendRelationshipReducer from "../remove_friend_relationship_reducer";
import RespondToFriendRequestReducer from "../respond_to_friend_request_reducer";
import SendCashToUserReducer from "../send_cash_to_user_reducer";
import SendFriendRequestReducer from "../send_friend_request_reducer";
import SendGlobalMessageReducer from "../send_global_message_reducer";
import SendThreadMessageReducer from "../send_thread_message_reducer";
import SetLivePresenceReducer from "../set_live_presence_reducer";
import SetSocialStatusReducer from "../set_social_status_reducer";
import StartLiveReducer from "../start_live_reducer";
import TickLiveEventReducer from "../tick_live_event_reducer";
import UnbanLiveUserReducer from "../unban_live_user_reducer";
import UpdateLiveReducer from "../update_live_reducer";
import UpsertAccountStateReducer from "../upsert_account_state_reducer";

export type BanLiveUserParams = __Infer<typeof BanLiveUserReducer>;
export type BoostLiveParams = __Infer<typeof BoostLiveReducer>;
export type CreateUserProfileParams = __Infer<typeof CreateUserProfileReducer>;
export type EndLiveParams = __Infer<typeof EndLiveReducer>;
export type GrantAdminCurrencyParams = __Infer<typeof GrantAdminCurrencyReducer>;
export type MarkConversationReadParams = __Infer<typeof MarkConversationReadReducer>;
export type RemoveFriendRelationshipParams = __Infer<typeof RemoveFriendRelationshipReducer>;
export type RespondToFriendRequestParams = __Infer<typeof RespondToFriendRequestReducer>;
export type SendCashToUserParams = __Infer<typeof SendCashToUserReducer>;
export type SendFriendRequestParams = __Infer<typeof SendFriendRequestReducer>;
export type SendGlobalMessageParams = __Infer<typeof SendGlobalMessageReducer>;
export type SendThreadMessageParams = __Infer<typeof SendThreadMessageReducer>;
export type SetLivePresenceParams = __Infer<typeof SetLivePresenceReducer>;
export type SetSocialStatusParams = __Infer<typeof SetSocialStatusReducer>;
export type StartLiveParams = __Infer<typeof StartLiveReducer>;
export type TickLiveEventParams = __Infer<typeof TickLiveEventReducer>;
export type UnbanLiveUserParams = __Infer<typeof UnbanLiveUserReducer>;
export type UpdateLiveParams = __Infer<typeof UpdateLiveReducer>;
export type UpsertAccountStateParams = __Infer<typeof UpsertAccountStateReducer>;

