import { radius, spacing, typography } from '../../../theme';

const adminPalette = {
  background: '#0B1020',
  surface: '#121A2B',
  surfaceAlt: '#182235',
  border: '#27324A',
  textPrimary: '#F3F6FF',
  textSecondary: '#AAB4CC',
  textMuted: '#8895B3',
  primary: '#3B82F6',
  success: '#22C55E',
  warning: '#F59E0B',
  danger: '#EF4444',
} as const;

export const adminTokens = {
  palette: adminPalette,
  colors: {
    pageBg: adminPalette.background,
    surface: adminPalette.surface,
    surfaceAlt: adminPalette.surfaceAlt,
    border: adminPalette.border,
    borderSubtle: adminPalette.border,
    textPrimary: adminPalette.textPrimary,
    textSecondary: adminPalette.textSecondary,
    textMuted: adminPalette.textMuted,
    primary: adminPalette.primary,
    primarySubtle: 'rgba(59, 130, 246, 0.16)',
    primaryBorder: 'rgba(59, 130, 246, 0.34)',
    info: adminPalette.primary,
    infoSubtle: 'rgba(59, 130, 246, 0.16)',
    infoBorder: 'rgba(59, 130, 246, 0.34)',
    accentPrimary: adminPalette.primary,
    accentPrimarySubtle: 'rgba(59, 130, 246, 0.16)',
    accentPrimaryBorder: 'rgba(59, 130, 246, 0.34)',
    success: adminPalette.success,
    successSubtle: 'rgba(34, 197, 94, 0.14)',
    successBorder: 'rgba(34, 197, 94, 0.32)',
    warning: adminPalette.warning,
    warningSubtle: 'rgba(245, 158, 11, 0.14)',
    warningBorder: 'rgba(245, 158, 11, 0.32)',
    danger: adminPalette.danger,
    dangerSubtle: 'rgba(239, 68, 68, 0.14)',
    dangerBorder: 'rgba(239, 68, 68, 0.32)',
    overlayScrim: 'rgba(11, 16, 32, 0.56)',
    overlaySheet: 'rgba(11, 16, 32, 0.46)',
  },
  spacing: {
    pageX: spacing.lg,
    pageY: spacing.lg,
    section: spacing.xl,
    card: spacing.lg,
    gapSm: spacing.sm,
    gapMd: spacing.md,
    gapLg: spacing.lg,
  },
  radius: {
    card: radius.md,
    chip: radius.full,
    input: radius.md,
    button: radius.md,
  },
  border: {
    width: 1,
    subtle: adminPalette.border,
  },
  typography: {
    pageTitle: typography.h2,
    pageDescription: typography.small,
    sectionTitle: typography.bodyBold,
    sectionDescription: typography.small,
    cardTitle: typography.bodyBold,
    cardSubtitle: typography.small,
    body: typography.body,
    caption: typography.tiny,
    badge: typography.micro,
  },
} as const;

export type AdminTone = 'neutral' | 'primary' | 'success' | 'warning' | 'danger';
