// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendAuditLogReducer from "../append_audit_log_reducer";
import AppendModerationActionReducer from "../append_moderation_action_reducer";
import BanLiveUserReducer from "../ban_live_user_reducer";
import BoostLiveReducer from "../boost_live_reducer";
import CreateUserProfileReducer from "../create_user_profile_reducer";
import DeleteGlobalMessageReducer from "../delete_global_message_reducer";
import EditGlobalMessageReducer from "../edit_global_message_reducer";
import EndLiveReducer from "../end_live_reducer";
import GrantAdminCurrencyReducer from "../grant_admin_currency_reducer";
import LinkIdentityToExistingUserReducer from "../link_identity_to_existing_user_reducer";
import MarkConversationReadReducer from "../mark_conversation_read_reducer";
import OnConnectReducer from "../on_connect_reducer";
import OnDisconnectReducer from "../on_disconnect_reducer";
import RemoveFriendRelationshipReducer from "../remove_friend_relationship_reducer";
import ResolveOrCreateUserIdentityReducer from "../resolve_or_create_user_identity_reducer";
import RespondToFriendRequestReducer from "../respond_to_friend_request_reducer";
import SendCashToUserReducer from "../send_cash_to_user_reducer";
import SendFriendRequestReducer from "../send_friend_request_reducer";
import SendGlobalMessageReducer from "../send_global_message_reducer";
import SendThreadMessageReducer from "../send_thread_message_reducer";
import SetEventWidgetConfigReducer from "../set_event_widget_config_reducer";
import SetEventWidgetEnabledReducer from "../set_event_widget_enabled_reducer";
import SetLivePresenceReducer from "../set_live_presence_reducer";
import SetSocialStatusReducer from "../set_social_status_reducer";
import SetUserRoleReducer from "../set_user_role_reducer";
import StartLiveReducer from "../start_live_reducer";
import SubmitWithdrawalRequestReducer from "../submit_withdrawal_request_reducer";
import TickLiveEventReducer from "../tick_live_event_reducer";
import UnbanLiveUserReducer from "../unban_live_user_reducer";
import UpdateLiveReducer from "../update_live_reducer";
import UpsertAccountStateReducer from "../upsert_account_state_reducer";

export type AppendAuditLogParams = __Infer<typeof AppendAuditLogReducer>;
export type AppendModerationActionParams = __Infer<typeof AppendModerationActionReducer>;
export type BanLiveUserParams = __Infer<typeof BanLiveUserReducer>;
export type BoostLiveParams = __Infer<typeof BoostLiveReducer>;
export type CreateUserProfileParams = __Infer<typeof CreateUserProfileReducer>;
export type DeleteGlobalMessageParams = __Infer<typeof DeleteGlobalMessageReducer>;
export type EditGlobalMessageParams = __Infer<typeof EditGlobalMessageReducer>;
export type EndLiveParams = __Infer<typeof EndLiveReducer>;
export type GrantAdminCurrencyParams = __Infer<typeof GrantAdminCurrencyReducer>;
export type LinkIdentityToExistingUserParams = __Infer<typeof LinkIdentityToExistingUserReducer>;
export type MarkConversationReadParams = __Infer<typeof MarkConversationReadReducer>;
export type OnConnectParams = __Infer<typeof OnConnectReducer>;
export type OnDisconnectParams = __Infer<typeof OnDisconnectReducer>;
export type RemoveFriendRelationshipParams = __Infer<typeof RemoveFriendRelationshipReducer>;
export type ResolveOrCreateUserIdentityParams = __Infer<typeof ResolveOrCreateUserIdentityReducer>;
export type RespondToFriendRequestParams = __Infer<typeof RespondToFriendRequestReducer>;
export type SendCashToUserParams = __Infer<typeof SendCashToUserReducer>;
export type SendFriendRequestParams = __Infer<typeof SendFriendRequestReducer>;
export type SendGlobalMessageParams = __Infer<typeof SendGlobalMessageReducer>;
export type SendThreadMessageParams = __Infer<typeof SendThreadMessageReducer>;
export type SetEventWidgetConfigParams = __Infer<typeof SetEventWidgetConfigReducer>;
export type SetEventWidgetEnabledParams = __Infer<typeof SetEventWidgetEnabledReducer>;
export type SetLivePresenceParams = __Infer<typeof SetLivePresenceReducer>;
export type SetSocialStatusParams = __Infer<typeof SetSocialStatusReducer>;
export type SetUserRoleParams = __Infer<typeof SetUserRoleReducer>;
export type StartLiveParams = __Infer<typeof StartLiveReducer>;
export type SubmitWithdrawalRequestParams = __Infer<typeof SubmitWithdrawalRequestReducer>;
export type TickLiveEventParams = __Infer<typeof TickLiveEventReducer>;
export type UnbanLiveUserParams = __Infer<typeof UnbanLiveUserReducer>;
export type UpdateLiveParams = __Infer<typeof UpdateLiveReducer>;
export type UpsertAccountStateParams = __Infer<typeof UpsertAccountStateReducer>;
