import {
  EARN_AD_WALL_COOLDOWN_MS,
  EARN_AD_WALL_REWARD_GEMS,
  EARN_STREAK_REWARDS,
} from './earnState';

export const AD_WALL_DURATION = EARN_AD_WALL_COOLDOWN_MS;
export const AD_WALL_REWARD = EARN_AD_WALL_REWARD_GEMS;
export const VIDEO_AD_DURATION = 1_500;
export const REWARDS = EARN_STREAK_REWARDS;
