// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  pairKey: __t.string().name("pair_key"),
  userLowId: __t.string().name("user_low_id"),
  userHighId: __t.string().name("user_high_id"),
  status: __t.string(),
  requestedBy: __t.option(__t.string()).name("requested_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
