// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  adminUserId: __t.string().name("admin_user_id"),
  targetUserId: __t.string().name("target_user_id"),
  deltaGems: __t.u32().name("delta_gems"),
  deltaCash: __t.u32().name("delta_cash"),
  deltaFuel: __t.u32().name("delta_fuel"),
  reason: __t.string(),
  balanceBefore: __t.string().name("balance_before"),
  balanceAfter: __t.string().name("balance_after"),
  metadata: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
