// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  connectionId: __t.string().primaryKey().name("connection_id"),
  senderIdentity: __t.string().name("sender_identity"),
  vuluUserId: __t.string().name("vulu_user_id"),
  connectedAt: __t.timestamp().name("connected_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
