// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  liveId: __t.string().name("live_id"),
  userId: __t.string().name("user_id"),
  dayBucketStartIsoUtc: __t.string().name("day_bucket_start_iso_utc"),
  activity: __t.string(),
  source: __t.string(),
  firstSeenAtIsoUtc: __t.string().name("first_seen_at_iso_utc"),
  lastSeenAtIsoUtc: __t.string().name("last_seen_at_iso_utc"),
});
