// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  bucketTimezone: __t.string().name("bucket_timezone"),
  asOfIsoUtc: __t.string().name("as_of_iso_utc"),
  todayStartIsoUtc: __t.string().name("today_start_iso_utc"),
  weekStartIsoUtc: __t.string().name("week_start_iso_utc"),
  monthStartIsoUtc: __t.string().name("month_start_iso_utc"),
  activeWindowMs: __t.u32().name("active_window_ms"),
  activePlayersNow: __t.u32().name("active_players_now"),
  totalPlayersToday: __t.u32().name("total_players_today"),
  totalPlayersWeek: __t.u32().name("total_players_week"),
  totalPlayersMonth: __t.u32().name("total_players_month"),
  totalEntriesToday: __t.u32().name("total_entries_today"),
  totalEntriesWeek: __t.u32().name("total_entries_week"),
  totalEntriesMonth: __t.u32().name("total_entries_month"),
});
