// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  enabled: __t.bool(),
  entryAmountCash: __t.u32().name("entry_amount_cash"),
  drawDurationMinutes: __t.u32().name("draw_duration_minutes"),
  drawIntervalMinutes: __t.u32().name("draw_interval_minutes"),
  autoplayEnabled: __t.bool().name("autoplay_enabled"),
  updatedBy: __t.string().name("updated_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
