// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import BanLiveUserReducer from "./ban_live_user_reducer";
import BoostLiveReducer from "./boost_live_reducer";
import CreateUserProfileReducer from "./create_user_profile_reducer";
import DeleteGlobalMessageReducer from "./delete_global_message_reducer";
import EditGlobalMessageReducer from "./edit_global_message_reducer";
import EndLiveReducer from "./end_live_reducer";
import GrantAdminCurrencyReducer from "./grant_admin_currency_reducer";
import LinkIdentityToExistingUserReducer from "./link_identity_to_existing_user_reducer";
import MarkConversationReadReducer from "./mark_conversation_read_reducer";
import RemoveFriendRelationshipReducer from "./remove_friend_relationship_reducer";
import ResolveOrCreateUserIdentityReducer from "./resolve_or_create_user_identity_reducer";
import RespondToFriendRequestReducer from "./respond_to_friend_request_reducer";
import SendCashToUserReducer from "./send_cash_to_user_reducer";
import SendFriendRequestReducer from "./send_friend_request_reducer";
import SendGlobalMessageReducer from "./send_global_message_reducer";
import SendThreadMessageReducer from "./send_thread_message_reducer";
import SetLivePresenceReducer from "./set_live_presence_reducer";
import SetSocialStatusReducer from "./set_social_status_reducer";
import SetUserRoleReducer from "./set_user_role_reducer";
import StartLiveReducer from "./start_live_reducer";
import TickLiveEventReducer from "./tick_live_event_reducer";
import UnbanLiveUserReducer from "./unban_live_user_reducer";
import UpdateLiveReducer from "./update_live_reducer";
import UpsertAccountStateReducer from "./upsert_account_state_reducer";

// Import all procedure arg schemas
import * as ResolveOrCreateUserIdentitySyncProcedure from "./resolve_or_create_user_identity_sync_procedure";

// Import all table schema definitions
import AccountStateItemRow from "./account_state_item_table";
import AdminWalletCreditTransactionRow from "./admin_wallet_credit_transaction_table";
import ArtistRow from "./artist_table";
import ConversationItemRow from "./conversation_item_table";
import FriendshipRow from "./friendship_table";
import GlobalMessageItemRow from "./global_message_item_table";
import KnownLiveUserItemRow from "./known_live_user_item_table";
import LeaderboardItemRow from "./leaderboard_item_table";
import LiveBoostLeaderboardItemRow from "./live_boost_leaderboard_item_table";
import LiveItemRow from "./live_item_table";
import LivePresenceItemRow from "./live_presence_item_table";
import MentionUserItemRow from "./mention_user_item_table";
import MyAccountStateRow from "./my_account_state_table";
import MyConversationMessagesRow from "./my_conversation_messages_table";
import MyConversationsRow from "./my_conversations_table";
import MyFriendshipsRow from "./my_friendships_table";
import MyIdentityRow from "./my_identity_table";
import MyNotificationsRow from "./my_notifications_table";
import MyProfileRow from "./my_profile_table";
import MyRolesRow from "./my_roles_table";
import NotificationItemRow from "./notification_item_table";
import PlaylistRow from "./playlist_table";
import PlaylistTrackRow from "./playlist_track_table";
import PublicLeaderboardRow from "./public_leaderboard_table";
import PublicLeaderboardItemRow from "./public_leaderboard_item_table";
import PublicLiveDiscoveryRow from "./public_live_discovery_table";
import PublicLiveDiscoveryItemRow from "./public_live_discovery_item_table";
import PublicProfileSummaryRow from "./public_profile_summary_table";
import PublicProfileSummaryItemRow from "./public_profile_summary_item_table";
import SocialUserItemRow from "./social_user_item_table";
import ThreadSeedMessageRow from "./thread_seed_message_table";
import TrackRow from "./track_table";
import UserIdentityRow from "./user_identity_table";
import UserProfileItemRow from "./user_profile_item_table";
import UserRoleRow from "./user_role_table";
import UsersRow from "./users_table";
import VideoItemRow from "./video_item_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  accountStateItem: __table({
    name: 'account_state_item',
    indexes: [
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'account_state_item_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, AccountStateItemRow),
  adminWalletCreditTransaction: __table({
    name: 'admin_wallet_credit_transaction',
    indexes: [
      { name: 'adminUserId', algorithm: 'btree', columns: [
        'adminUserId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'targetUserId', algorithm: 'btree', columns: [
        'targetUserId',
      ] },
    ],
    constraints: [
      { name: 'admin_wallet_credit_transaction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AdminWalletCreditTransactionRow),
  artist: __table({
    name: 'artist',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'artist_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ArtistRow),
  conversationItem: __table({
    name: 'conversation_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'otherUserId', algorithm: 'btree', columns: [
        'otherUserId',
      ] },
      { name: 'ownerUserId', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'conversation_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConversationItemRow),
  friendship: __table({
    name: 'friendship',
    indexes: [
      { name: 'pairKey', algorithm: 'btree', columns: [
        'pairKey',
      ] },
      { name: 'userHighId', algorithm: 'btree', columns: [
        'userHighId',
      ] },
      { name: 'userLowId', algorithm: 'btree', columns: [
        'userLowId',
      ] },
    ],
    constraints: [
      { name: 'friendship_pair_key_key', constraint: 'unique', columns: ['pairKey'] },
    ],
  }, FriendshipRow),
  globalMessageItem: __table({
    name: 'global_message_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'roomId', algorithm: 'btree', columns: [
        'roomId',
      ] },
    ],
    constraints: [
      { name: 'global_message_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GlobalMessageItemRow),
  knownLiveUserItem: __table({
    name: 'known_live_user_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'known_live_user_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KnownLiveUserItemRow),
  leaderboardItem: __table({
    name: 'leaderboard_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'leaderboard_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LeaderboardItemRow),
  liveBoostLeaderboardItem: __table({
    name: 'live_boost_leaderboard_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'live_boost_leaderboard_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LiveBoostLeaderboardItemRow),
  liveItem: __table({
    name: 'live_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'live_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LiveItemRow),
  livePresenceItem: __table({
    name: 'live_presence_item',
    indexes: [
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'live_presence_item_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, LivePresenceItemRow),
  mentionUserItem: __table({
    name: 'mention_user_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'mention_user_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MentionUserItemRow),
  notificationItem: __table({
    name: 'notification_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'notification_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NotificationItemRow),
  playlist: __table({
    name: 'playlist',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'playlist_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlaylistRow),
  playlistTrack: __table({
    name: 'playlist_track',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'playlistId', algorithm: 'btree', columns: [
        'playlistId',
      ] },
      { name: 'trackId', algorithm: 'btree', columns: [
        'trackId',
      ] },
    ],
    constraints: [
      { name: 'playlist_track_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlaylistTrackRow),
  publicLeaderboardItem: __table({
    name: 'public_leaderboard_item',
    indexes: [
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'public_leaderboard_item_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, PublicLeaderboardItemRow),
  publicLiveDiscoveryItem: __table({
    name: 'public_live_discovery_item',
    indexes: [
      { name: 'liveId', algorithm: 'btree', columns: [
        'liveId',
      ] },
    ],
    constraints: [
      { name: 'public_live_discovery_item_live_id_key', constraint: 'unique', columns: ['liveId'] },
    ],
  }, PublicLiveDiscoveryItemRow),
  publicProfileSummaryItem: __table({
    name: 'public_profile_summary_item',
    indexes: [
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'public_profile_summary_item_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, PublicProfileSummaryItemRow),
  socialUserItem: __table({
    name: 'social_user_item',
    indexes: [
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'social_user_item_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, SocialUserItemRow),
  threadSeedMessage: __table({
    name: 'thread_seed_message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'otherUserId', algorithm: 'btree', columns: [
        'otherUserId',
      ] },
      { name: 'ownerUserId', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
    ],
    constraints: [
      { name: 'thread_seed_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ThreadSeedMessageRow),
  track: __table({
    name: 'track',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'track_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TrackRow),
  userIdentity: __table({
    name: 'user_identity',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'lookupKey', algorithm: 'btree', columns: [
        'lookupKey',
      ] },
      { name: 'vuluUserId', algorithm: 'btree', columns: [
        'vuluUserId',
      ] },
    ],
    constraints: [
      { name: 'user_identity_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'user_identity_lookup_key_key', constraint: 'unique', columns: ['lookupKey'] },
    ],
  }, UserIdentityRow),
  userProfileItem: __table({
    name: 'user_profile_item',
    indexes: [
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_profile_item_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UserProfileItemRow),
  userRole: __table({
    name: 'user_role',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'vuluUserId', algorithm: 'btree', columns: [
        'vuluUserId',
      ] },
    ],
    constraints: [
      { name: 'user_role_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UserRoleRow),
  users: __table({
    name: 'users',
    indexes: [
      { name: 'vuluUserId', algorithm: 'btree', columns: [
        'vuluUserId',
      ] },
    ],
    constraints: [
      { name: 'users_vulu_user_id_key', constraint: 'unique', columns: ['vuluUserId'] },
    ],
  }, UsersRow),
  videoItem: __table({
    name: 'video_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'video_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VideoItemRow),
  myAccountState: __table({
    name: 'my_account_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAccountStateRow),
  myConversationMessages: __table({
    name: 'my_conversation_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyConversationMessagesRow),
  myConversations: __table({
    name: 'my_conversations',
    indexes: [
    ],
    constraints: [
    ],
  }, MyConversationsRow),
  myFriendships: __table({
    name: 'my_friendships',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendshipsRow),
  myIdentity: __table({
    name: 'my_identity',
    indexes: [
    ],
    constraints: [
    ],
  }, MyIdentityRow),
  myNotifications: __table({
    name: 'my_notifications',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNotificationsRow),
  myProfile: __table({
    name: 'my_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProfileRow),
  myRoles: __table({
    name: 'my_roles',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRolesRow),
  publicLeaderboard: __table({
    name: 'public_leaderboard',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicLeaderboardRow),
  publicLiveDiscovery: __table({
    name: 'public_live_discovery',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicLiveDiscoveryRow),
  publicProfileSummary: __table({
    name: 'public_profile_summary',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicProfileSummaryRow),
});

const toModuleSourceName = (accessorName: string): string =>
  accessorName.replace(/[A-Z]/g, (match) => `_${match.toLowerCase()}`);

for (const [accessorName, tableDef] of Object.entries(tablesSchema.schemaType.tables)) {
  // The generated SDK currently keys runtime row parsing off `sourceName`, but
  // codegen emits accessor names (`myIdentity`) there instead of module names
  // (`my_identity`). Normalize them here so subscription snapshots decode.
  (tableDef as { sourceName: string }).sourceName = toModuleSourceName(accessorName);
}

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("ban_live_user", BanLiveUserReducer),
  __reducerSchema("boost_live", BoostLiveReducer),
  __reducerSchema("create_user_profile", CreateUserProfileReducer),
  __reducerSchema("delete_global_message", DeleteGlobalMessageReducer),
  __reducerSchema("edit_global_message", EditGlobalMessageReducer),
  __reducerSchema("end_live", EndLiveReducer),
  __reducerSchema("grant_admin_currency", GrantAdminCurrencyReducer),
  __reducerSchema("link_identity_to_existing_user", LinkIdentityToExistingUserReducer),
  __reducerSchema("mark_conversation_read", MarkConversationReadReducer),
  __reducerSchema("remove_friend_relationship", RemoveFriendRelationshipReducer),
  __reducerSchema("resolve_or_create_user_identity", ResolveOrCreateUserIdentityReducer),
  __reducerSchema("respond_to_friend_request", RespondToFriendRequestReducer),
  __reducerSchema("send_cash_to_user", SendCashToUserReducer),
  __reducerSchema("send_friend_request", SendFriendRequestReducer),
  __reducerSchema("send_global_message", SendGlobalMessageReducer),
  __reducerSchema("send_thread_message", SendThreadMessageReducer),
  __reducerSchema("set_live_presence", SetLivePresenceReducer),
  __reducerSchema("set_social_status", SetSocialStatusReducer),
  __reducerSchema("set_user_role", SetUserRoleReducer),
  __reducerSchema("start_live", StartLiveReducer),
  __reducerSchema("tick_live_event", TickLiveEventReducer),
  __reducerSchema("unban_live_user", UnbanLiveUserReducer),
  __reducerSchema("update_live", UpdateLiveReducer),
  __reducerSchema("upsert_account_state", UpsertAccountStateReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("resolve_or_create_user_identity_sync", ResolveOrCreateUserIdentitySyncProcedure.params, ResolveOrCreateUserIdentitySyncProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
