// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  viewerUserId: __t.string().name("viewer_user_id"),
  profileUserId: __t.string().name("profile_user_id"),
  metricVersion: __t.string().name("metric_version"),
  occurredAtMs: __t.string().name("occurred_at_ms"),
  dedupeWindowMs: __t.u32().name("dedupe_window_ms"),
  counted: __t.bool(),
  dropReason: __t.option(__t.string()).name("drop_reason"),
  source: __t.option(__t.string()),
  createdAt: __t.timestamp().name("created_at"),
});
