// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  metricName: __t.string().primaryKey().name("metric_name"),
  activeVersion: __t.string().name("active_version"),
  cutoverAtMs: __t.string().name("cutover_at_ms"),
  dedupeWindowMs: __t.u32().name("dedupe_window_ms"),
  migrationMode: __t.string().name("migration_mode"),
  notes: __t.option(__t.string()),
  updatedBy: __t.option(__t.string()).name("updated_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
