// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  profileUserId: __t.string().primaryKey().name("profile_user_id"),
  countedTotal: __t.u32().name("counted_total"),
  uniqueViewerTotal: __t.u32().name("unique_viewer_total"),
  lastCountedAtMs: __t.string().name("last_counted_at_ms"),
  updatedAt: __t.timestamp().name("updated_at"),
});
