// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  profileUserId: __t.string().name("profile_user_id"),
  viewerUserId: __t.string().name("viewer_user_id"),
  firstCountedAtMs: __t.string().name("first_counted_at_ms"),
  lastCountedAtMs: __t.string().name("last_counted_at_ms"),
  viewCount: __t.u32().name("view_count"),
  updatedAt: __t.timestamp().name("updated_at"),
});
