// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  liveId: __t.string().name("live_id"),
  hostUserId: __t.option(__t.string()).name("host_user_id"),
  hostUsername: __t.option(__t.string()).name("host_username"),
  hostAvatarUrl: __t.option(__t.string()).name("host_avatar_url"),
  title: __t.string(),
  viewerCount: __t.u32().name("viewer_count"),
});
