// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  reporterUserId: __t.string().name("reporter_user_id"),
  targetType: __t.string().name("target_type"),
  targetId: __t.string().name("target_id"),
  reportedUserId: __t.option(__t.string()).name("reported_user_id"),
  surface: __t.string(),
  reason: __t.string(),
  details: __t.option(__t.string()),
  contextJson: __t.string().name("context_json"),
  status: __t.string(),
  reviewedBy: __t.option(__t.string()).name("reviewed_by"),
  reviewNotes: __t.option(__t.string()).name("review_notes"),
  reviewedAtIsoUtc: __t.option(__t.string()).name("reviewed_at_iso_utc"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
