// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  fromUserId: __t.string(),
  toUserId: __t.string(),
  amountCash: __t.u32(),
  note: __t.option(__t.string()),
  fromUserName: __t.option(__t.string()),
  fromUserAvatar: __t.option(__t.string()),
  messageId: __t.option(__t.string()),
};
