// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountStateItem = __t.object("AccountStateItem", {
  userId: __t.string(),
  state: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AccountStateItem = __Infer<typeof AccountStateItem>;

export const AdminWalletCreditTransaction = __t.object("AdminWalletCreditTransaction", {
  id: __t.string(),
  adminUserId: __t.string(),
  targetUserId: __t.string(),
  deltaGems: __t.u32(),
  deltaCash: __t.u32(),
  deltaFuel: __t.u32(),
  reason: __t.string(),
  balanceBefore: __t.string(),
  balanceAfter: __t.string(),
  metadata: __t.string(),
  createdAt: __t.timestamp(),
});
export type AdminWalletCreditTransaction = __Infer<typeof AdminWalletCreditTransaction>;

export const Artist = __t.object("Artist", {
  id: __t.string(),
  name: __t.string(),
  imageUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Artist = __Infer<typeof Artist>;

export const AuditLogItem = __t.object("AuditLogItem", {
  id: __t.string(),
  actorUserId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type AuditLogItem = __Infer<typeof AuditLogItem>;

export const ConnectionSessionItem = __t.object("ConnectionSessionItem", {
  connectionId: __t.string(),
  senderIdentity: __t.string(),
  vuluUserId: __t.string(),
  connectedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ConnectionSessionItem = __Infer<typeof ConnectionSessionItem>;

export const ConversationItem = __t.object("ConversationItem", {
  id: __t.string(),
  ownerUserId: __t.string(),
  otherUserId: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ConversationItem = __Infer<typeof ConversationItem>;

export const EventMetricsOverview = __t.object("EventMetricsOverview", {});
export type EventMetricsOverview = __Infer<typeof EventMetricsOverview>;

export const EventMetricsOverviewRow = __t.object("EventMetricsOverviewRow", {
  bucketTimezone: __t.string(),
  asOfIsoUtc: __t.string(),
  todayStartIsoUtc: __t.string(),
  weekStartIsoUtc: __t.string(),
  monthStartIsoUtc: __t.string(),
  activeWindowMs: __t.u32(),
  activePlayersNow: __t.u32(),
  totalPlayersToday: __t.u32(),
  totalPlayersWeek: __t.u32(),
  totalPlayersMonth: __t.u32(),
  totalEntriesToday: __t.u32(),
  totalEntriesWeek: __t.u32(),
  totalEntriesMonth: __t.u32(),
});
export type EventMetricsOverviewRow = __Infer<typeof EventMetricsOverviewRow>;

export const EventParticipationItem = __t.object("EventParticipationItem", {
  id: __t.string(),
  liveId: __t.string(),
  userId: __t.string(),
  dayBucketStartIsoUtc: __t.string(),
  activity: __t.string(),
  source: __t.string(),
  firstSeenAtIsoUtc: __t.string(),
  lastSeenAtIsoUtc: __t.string(),
});
export type EventParticipationItem = __Infer<typeof EventParticipationItem>;

export const EventWidgetConfigAuditItem = __t.object("EventWidgetConfigAuditItem", {
  id: __t.string(),
  action: __t.string(),
  actorUserId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type EventWidgetConfigAuditItem = __Infer<typeof EventWidgetConfigAuditItem>;

export const EventWidgetConfigItem = __t.object("EventWidgetConfigItem", {
  id: __t.string(),
  enabled: __t.bool(),
  entryAmountCash: __t.u32(),
  drawDurationMinutes: __t.u32(),
  drawIntervalMinutes: __t.u32(),
  autoplayEnabled: __t.bool(),
  updatedBy: __t.string(),
  updatedAt: __t.timestamp(),
});
export type EventWidgetConfigItem = __Infer<typeof EventWidgetConfigItem>;

export const Friendship = __t.object("Friendship", {
  pairKey: __t.string(),
  userLowId: __t.string(),
  userHighId: __t.string(),
  status: __t.string(),
  requestedBy: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type Friendship = __Infer<typeof Friendship>;

export const GlobalMessageItem = __t.object("GlobalMessageItem", {
  id: __t.string(),
  roomId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type GlobalMessageItem = __Infer<typeof GlobalMessageItem>;

export const KnownLiveUserItem = __t.object("KnownLiveUserItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type KnownLiveUserItem = __Infer<typeof KnownLiveUserItem>;

export const LeaderboardItem = __t.object("LeaderboardItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LeaderboardItem = __Infer<typeof LeaderboardItem>;

export const LiveBoostLeaderboardItem = __t.object("LiveBoostLeaderboardItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LiveBoostLeaderboardItem = __Infer<typeof LiveBoostLeaderboardItem>;

export const LiveItem = __t.object("LiveItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LiveItem = __Infer<typeof LiveItem>;

export const LivePresenceItem = __t.object("LivePresenceItem", {
  userId: __t.string(),
  liveId: __t.option(__t.string()),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LivePresenceItem = __Infer<typeof LivePresenceItem>;

export const MentionUserItem = __t.object("MentionUserItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MentionUserItem = __Infer<typeof MentionUserItem>;

export const ModerationActionItem = __t.object("ModerationActionItem", {
  id: __t.string(),
  actorUserId: __t.string(),
  targetUserId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type ModerationActionItem = __Infer<typeof ModerationActionItem>;

export const MyAccountState = __t.object("MyAccountState", {});
export type MyAccountState = __Infer<typeof MyAccountState>;

export const MyAccountStateRow = __t.object("MyAccountStateRow", {
  userId: __t.string(),
  state: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MyAccountStateRow = __Infer<typeof MyAccountStateRow>;

export const MyConversationMessageRow = __t.object("MyConversationMessageRow", {
  id: __t.string(),
  ownerUserId: __t.string(),
  otherUserId: __t.string(),
  messages: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MyConversationMessageRow = __Infer<typeof MyConversationMessageRow>;

export const MyConversationMessages = __t.object("MyConversationMessages", {});
export type MyConversationMessages = __Infer<typeof MyConversationMessages>;

export const MyConversationRow = __t.object("MyConversationRow", {
  id: __t.string(),
  ownerUserId: __t.string(),
  otherUserId: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MyConversationRow = __Infer<typeof MyConversationRow>;

export const MyConversations = __t.object("MyConversations", {});
export type MyConversations = __Infer<typeof MyConversations>;

export const MyFriendshipRow = __t.object("MyFriendshipRow", {
  pairKey: __t.string(),
  userLowId: __t.string(),
  userHighId: __t.string(),
  status: __t.string(),
  requestedBy: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type MyFriendshipRow = __Infer<typeof MyFriendshipRow>;

export const MyFriendships = __t.object("MyFriendships", {});
export type MyFriendships = __Infer<typeof MyFriendships>;

export const MyIdentity = __t.object("MyIdentity", {});
export type MyIdentity = __Infer<typeof MyIdentity>;

export const MyIdentityRow = __t.object("MyIdentityRow", {
  id: __t.string(),
  vuluUserId: __t.string(),
  provider: __t.string(),
  issuer: __t.string(),
  subject: __t.string(),
  email: __t.option(__t.string()),
  emailVerified: __t.bool(),
  createdAt: __t.timestamp(),
});
export type MyIdentityRow = __Infer<typeof MyIdentityRow>;

export const MyNotificationRow = __t.object("MyNotificationRow", {
  id: __t.string(),
  userId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type MyNotificationRow = __Infer<typeof MyNotificationRow>;

export const MyNotifications = __t.object("MyNotifications", {});
export type MyNotifications = __Infer<typeof MyNotifications>;

export const MyProfile = __t.object("MyProfile", {});
export type MyProfile = __Infer<typeof MyProfile>;

export const MyProfileRow = __t.object("MyProfileRow", {
  userId: __t.string(),
  profile: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MyProfileRow = __Infer<typeof MyProfileRow>;

export const MyRoleRow = __t.object("MyRoleRow", {
  id: __t.string(),
  vuluUserId: __t.string(),
  role: __t.string(),
  grantedAt: __t.timestamp(),
  grantedBy: __t.option(__t.string()),
});
export type MyRoleRow = __Infer<typeof MyRoleRow>;

export const MyRoles = __t.object("MyRoles", {});
export type MyRoles = __Infer<typeof MyRoles>;

export const MySubmittedReports = __t.object("MySubmittedReports", {});
export type MySubmittedReports = __Infer<typeof MySubmittedReports>;

export const MyWalletBalance = __t.object("MyWalletBalance", {});
export type MyWalletBalance = __Infer<typeof MyWalletBalance>;

export const MyWalletBalanceRow = __t.object("MyWalletBalanceRow", {
  userId: __t.string(),
  gems: __t.u32(),
  cash: __t.u32(),
  fuel: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type MyWalletBalanceRow = __Infer<typeof MyWalletBalanceRow>;

export const MyWalletTransactionRow = __t.object("MyWalletTransactionRow", {
  id: __t.string(),
  userId: __t.string(),
  eventType: __t.string(),
  deltaGems: __t.i32(),
  deltaCash: __t.i32(),
  deltaFuel: __t.i32(),
  balanceBefore: __t.string(),
  balanceAfter: __t.string(),
  metadata: __t.string(),
  createdAt: __t.timestamp(),
});
export type MyWalletTransactionRow = __Infer<typeof MyWalletTransactionRow>;

export const MyWalletTransactions = __t.object("MyWalletTransactions", {});
export type MyWalletTransactions = __Infer<typeof MyWalletTransactions>;

export const NotificationItem = __t.object("NotificationItem", {
  id: __t.string(),
  userId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type NotificationItem = __Infer<typeof NotificationItem>;

export const Playlist = __t.object("Playlist", {
  id: __t.string(),
  title: __t.string(),
  description: __t.option(__t.string()),
  coverUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Playlist = __Infer<typeof Playlist>;

export const PlaylistTrack = __t.object("PlaylistTrack", {
  id: __t.string(),
  playlistId: __t.string(),
  trackId: __t.string(),
  position: __t.u32(),
});
export type PlaylistTrack = __Infer<typeof PlaylistTrack>;

export const ProfileViewAggregateV2Item = __t.object("ProfileViewAggregateV2Item", {
  profileUserId: __t.string(),
  countedTotal: __t.u32(),
  uniqueViewerTotal: __t.u32(),
  lastCountedAtMs: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ProfileViewAggregateV2Item = __Infer<typeof ProfileViewAggregateV2Item>;

export const ProfileViewAttemptV2Item = __t.object("ProfileViewAttemptV2Item", {
  id: __t.string(),
  viewerUserId: __t.string(),
  profileUserId: __t.string(),
  metricVersion: __t.string(),
  occurredAtMs: __t.string(),
  dedupeWindowMs: __t.u32(),
  counted: __t.bool(),
  dropReason: __t.option(__t.string()),
  source: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type ProfileViewAttemptV2Item = __Infer<typeof ProfileViewAttemptV2Item>;

export const ProfileViewDedupeStateV2Item = __t.object("ProfileViewDedupeStateV2Item", {
  key: __t.string(),
  viewerUserId: __t.string(),
  profileUserId: __t.string(),
  lastCountedAtMs: __t.string(),
  lastEventId: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ProfileViewDedupeStateV2Item = __Infer<typeof ProfileViewDedupeStateV2Item>;

export const ProfileViewMetricCutoverItem = __t.object("ProfileViewMetricCutoverItem", {
  metricName: __t.string(),
  activeVersion: __t.string(),
  cutoverAtMs: __t.string(),
  dedupeWindowMs: __t.u32(),
  migrationMode: __t.string(),
  notes: __t.option(__t.string()),
  updatedBy: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type ProfileViewMetricCutoverItem = __Infer<typeof ProfileViewMetricCutoverItem>;

export const ProfileViewUniqueViewerV2Item = __t.object("ProfileViewUniqueViewerV2Item", {
  key: __t.string(),
  profileUserId: __t.string(),
  viewerUserId: __t.string(),
  firstCountedAtMs: __t.string(),
  lastCountedAtMs: __t.string(),
  viewCount: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type ProfileViewUniqueViewerV2Item = __Infer<typeof ProfileViewUniqueViewerV2Item>;

export const PublicLeaderboard = __t.object("PublicLeaderboard", {});
export type PublicLeaderboard = __Infer<typeof PublicLeaderboard>;

export const PublicLeaderboardItem = __t.object("PublicLeaderboardItem", {
  userId: __t.string(),
  score: __t.u32(),
  gold: __t.u32(),
  gems: __t.u32(),
});
export type PublicLeaderboardItem = __Infer<typeof PublicLeaderboardItem>;

export const PublicLeaderboardRow = __t.object("PublicLeaderboardRow", {
  userId: __t.string(),
  username: __t.string(),
  displayName: __t.string(),
  avatarUrl: __t.string(),
  score: __t.u32(),
  gold: __t.u32(),
  gems: __t.u32(),
});
export type PublicLeaderboardRow = __Infer<typeof PublicLeaderboardRow>;

export const PublicLiveDiscovery = __t.object("PublicLiveDiscovery", {});
export type PublicLiveDiscovery = __Infer<typeof PublicLiveDiscovery>;

export const PublicLiveDiscoveryItem = __t.object("PublicLiveDiscoveryItem", {
  liveId: __t.string(),
  hostUserId: __t.option(__t.string()),
  hostUsername: __t.option(__t.string()),
  hostAvatarUrl: __t.option(__t.string()),
  title: __t.string(),
  viewerCount: __t.u32(),
});
export type PublicLiveDiscoveryItem = __Infer<typeof PublicLiveDiscoveryItem>;

export const PublicLiveDiscoveryRow = __t.object("PublicLiveDiscoveryRow", {
  liveId: __t.string(),
  hostUserId: __t.option(__t.string()),
  hostUsername: __t.option(__t.string()),
  hostAvatarUrl: __t.option(__t.string()),
  title: __t.string(),
  viewerCount: __t.u32(),
});
export type PublicLiveDiscoveryRow = __Infer<typeof PublicLiveDiscoveryRow>;

export const PublicLivePresenceItem = __t.object("PublicLivePresenceItem", {
  userId: __t.string(),
  liveId: __t.string(),
  activity: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PublicLivePresenceItem = __Infer<typeof PublicLivePresenceItem>;

export const PublicProfileSummary = __t.object("PublicProfileSummary", {});
export type PublicProfileSummary = __Infer<typeof PublicProfileSummary>;

export const PublicProfileSummaryItem = __t.object("PublicProfileSummaryItem", {
  userId: __t.string(),
  username: __t.string(),
  avatarUrl: __t.string(),
  badge: __t.option(__t.string()),
  spotlightStatus: __t.option(__t.string()),
});
export type PublicProfileSummaryItem = __Infer<typeof PublicProfileSummaryItem>;

export const PublicProfileSummaryRow = __t.object("PublicProfileSummaryRow", {
  userId: __t.string(),
  username: __t.string(),
  avatarUrl: __t.string(),
  badge: __t.option(__t.string()),
  spotlightStatus: __t.option(__t.string()),
});
export type PublicProfileSummaryRow = __Infer<typeof PublicProfileSummaryRow>;

export const ReportItem = __t.object("ReportItem", {
  id: __t.string(),
  reporterUserId: __t.string(),
  targetType: __t.string(),
  targetId: __t.string(),
  reportedUserId: __t.option(__t.string()),
  surface: __t.string(),
  reason: __t.string(),
  details: __t.option(__t.string()),
  contextJson: __t.string(),
  status: __t.string(),
  reviewedBy: __t.option(__t.string()),
  reviewNotes: __t.option(__t.string()),
  reviewedAtIsoUtc: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ReportItem = __Infer<typeof ReportItem>;

export const ReportViewRow = __t.object("ReportViewRow", {
  id: __t.string(),
  reporterUserId: __t.string(),
  targetType: __t.string(),
  targetId: __t.string(),
  reportedUserId: __t.option(__t.string()),
  surface: __t.string(),
  reason: __t.string(),
  details: __t.option(__t.string()),
  contextJson: __t.string(),
  status: __t.string(),
  reviewedBy: __t.option(__t.string()),
  reviewNotes: __t.option(__t.string()),
  reviewedAtIsoUtc: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ReportViewRow = __Infer<typeof ReportViewRow>;

export const SenderIdentityUserMap = __t.object("SenderIdentityUserMap", {
  senderIdentity: __t.string(),
  vuluUserId: __t.string(),
  updatedAt: __t.timestamp(),
});
export type SenderIdentityUserMap = __Infer<typeof SenderIdentityUserMap>;

export const SocialUserItem = __t.object("SocialUserItem", {
  userId: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type SocialUserItem = __Infer<typeof SocialUserItem>;

export const ThreadSeedMessage = __t.object("ThreadSeedMessage", {
  id: __t.string(),
  ownerUserId: __t.string(),
  otherUserId: __t.string(),
  messages: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ThreadSeedMessage = __Infer<typeof ThreadSeedMessage>;

export const Track = __t.object("Track", {
  id: __t.string(),
  title: __t.string(),
  artistId: __t.option(__t.string()),
  artworkUrl: __t.option(__t.string()),
  durationSeconds: __t.u32(),
  audioUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Track = __Infer<typeof Track>;

export const UserIdentity = __t.object("UserIdentity", {
  id: __t.string(),
  vuluUserId: __t.string(),
  provider: __t.string(),
  issuer: __t.string(),
  subject: __t.string(),
  email: __t.option(__t.string()),
  emailVerified: __t.bool(),
  lookupKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type UserIdentity = __Infer<typeof UserIdentity>;

export const UserProfileItem = __t.object("UserProfileItem", {
  userId: __t.string(),
  profile: __t.string(),
  updatedAt: __t.timestamp(),
});
export type UserProfileItem = __Infer<typeof UserProfileItem>;

export const UserRole = __t.object("UserRole", {
  id: __t.string(),
  vuluUserId: __t.string(),
  role: __t.string(),
  grantedAt: __t.timestamp(),
  grantedBy: __t.option(__t.string()),
});
export type UserRole = __Infer<typeof UserRole>;

export const Users = __t.object("Users", {
  vuluUserId: __t.string(),
  createdAt: __t.timestamp(),
  displayName: __t.string(),
  avatar: __t.option(__t.string()),
  isBanned: __t.bool(),
  banStatus: __t.string(),
  banReason: __t.option(__t.string()),
});
export type Users = __Infer<typeof Users>;

export const VideoItem = __t.object("VideoItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type VideoItem = __Infer<typeof VideoItem>;

export const WalletTransactionItem = __t.object("WalletTransactionItem", {
  id: __t.string(),
  userId: __t.string(),
  eventType: __t.string(),
  deltaGems: __t.i32(),
  deltaCash: __t.i32(),
  deltaFuel: __t.i32(),
  balanceBefore: __t.string(),
  balanceAfter: __t.string(),
  metadata: __t.string(),
  createdAt: __t.timestamp(),
});
export type WalletTransactionItem = __Infer<typeof WalletTransactionItem>;

export const WithdrawalRequestItem = __t.object("WithdrawalRequestItem", {
  id: __t.string(),
  userId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type WithdrawalRequestItem = __Infer<typeof WithdrawalRequestItem>;

