// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccountStateItem = __t.object("AccountStateItem", {
  userId: __t.string(),
  state: __t.string(),
  updatedAt: __t.timestamp(),
});
export type AccountStateItem = __Infer<typeof AccountStateItem>;

export const AdminWalletCreditTransaction = __t.object("AdminWalletCreditTransaction", {
  id: __t.string(),
  adminUserId: __t.string(),
  targetUserId: __t.string(),
  deltaGems: __t.u32(),
  deltaCash: __t.u32(),
  deltaFuel: __t.u32(),
  reason: __t.string(),
  balanceBefore: __t.string(),
  balanceAfter: __t.string(),
  metadata: __t.string(),
  createdAt: __t.timestamp(),
});
export type AdminWalletCreditTransaction = __Infer<typeof AdminWalletCreditTransaction>;

export const Artist = __t.object("Artist", {
  id: __t.string(),
  name: __t.string(),
  imageUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Artist = __Infer<typeof Artist>;

export const ConversationItem = __t.object("ConversationItem", {
  id: __t.string(),
  ownerUserId: __t.string(),
  otherUserId: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ConversationItem = __Infer<typeof ConversationItem>;

export const Friendship = __t.object("Friendship", {
  pairKey: __t.string(),
  userLowId: __t.string(),
  userHighId: __t.string(),
  status: __t.string(),
  requestedBy: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type Friendship = __Infer<typeof Friendship>;

export const GlobalMessageItem = __t.object("GlobalMessageItem", {
  id: __t.string(),
  roomId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type GlobalMessageItem = __Infer<typeof GlobalMessageItem>;

export const KnownLiveUserItem = __t.object("KnownLiveUserItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type KnownLiveUserItem = __Infer<typeof KnownLiveUserItem>;

export const LeaderboardItem = __t.object("LeaderboardItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LeaderboardItem = __Infer<typeof LeaderboardItem>;

export const LiveBoostLeaderboardItem = __t.object("LiveBoostLeaderboardItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LiveBoostLeaderboardItem = __Infer<typeof LiveBoostLeaderboardItem>;

export const LiveItem = __t.object("LiveItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LiveItem = __Infer<typeof LiveItem>;

export const LivePresenceItem = __t.object("LivePresenceItem", {
  userId: __t.string(),
  liveId: __t.option(__t.string()),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type LivePresenceItem = __Infer<typeof LivePresenceItem>;

export const MentionUserItem = __t.object("MentionUserItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MentionUserItem = __Infer<typeof MentionUserItem>;

export const MyAccountState = __t.object("MyAccountState", {});
export type MyAccountState = __Infer<typeof MyAccountState>;

export const MyAccountStateRow = __t.object("MyAccountStateRow", {
  userId: __t.string(),
  state: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MyAccountStateRow = __Infer<typeof MyAccountStateRow>;

export const MyConversationMessageRow = __t.object("MyConversationMessageRow", {
  id: __t.string(),
  ownerUserId: __t.string(),
  otherUserId: __t.string(),
  messages: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MyConversationMessageRow = __Infer<typeof MyConversationMessageRow>;

export const MyConversationMessages = __t.object("MyConversationMessages", {});
export type MyConversationMessages = __Infer<typeof MyConversationMessages>;

export const MyConversationRow = __t.object("MyConversationRow", {
  id: __t.string(),
  ownerUserId: __t.string(),
  otherUserId: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MyConversationRow = __Infer<typeof MyConversationRow>;

export const MyConversations = __t.object("MyConversations", {});
export type MyConversations = __Infer<typeof MyConversations>;

export const MyFriendshipRow = __t.object("MyFriendshipRow", {
  pairKey: __t.string(),
  userLowId: __t.string(),
  userHighId: __t.string(),
  status: __t.string(),
  requestedBy: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type MyFriendshipRow = __Infer<typeof MyFriendshipRow>;

export const MyFriendships = __t.object("MyFriendships", {});
export type MyFriendships = __Infer<typeof MyFriendships>;

export const MyNotificationRow = __t.object("MyNotificationRow", {
  id: __t.string(),
  userId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type MyNotificationRow = __Infer<typeof MyNotificationRow>;

export const MyNotifications = __t.object("MyNotifications", {});
export type MyNotifications = __Infer<typeof MyNotifications>;

export const NotificationItem = __t.object("NotificationItem", {
  id: __t.string(),
  userId: __t.string(),
  item: __t.string(),
  createdAt: __t.timestamp(),
});
export type NotificationItem = __Infer<typeof NotificationItem>;

export const Playlist = __t.object("Playlist", {
  id: __t.string(),
  title: __t.string(),
  description: __t.option(__t.string()),
  coverUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Playlist = __Infer<typeof Playlist>;

export const PlaylistTrack = __t.object("PlaylistTrack", {
  id: __t.string(),
  playlistId: __t.string(),
  trackId: __t.string(),
  position: __t.u32(),
});
export type PlaylistTrack = __Infer<typeof PlaylistTrack>;

export const PublicLeaderboard = __t.object("PublicLeaderboard", {});
export type PublicLeaderboard = __Infer<typeof PublicLeaderboard>;

export const PublicLeaderboardItem = __t.object("PublicLeaderboardItem", {
  userId: __t.string(),
  score: __t.u32(),
  gold: __t.u32(),
  gems: __t.u32(),
});
export type PublicLeaderboardItem = __Infer<typeof PublicLeaderboardItem>;

export const PublicLeaderboardRow = __t.object("PublicLeaderboardRow", {
  userId: __t.string(),
  score: __t.u32(),
  gold: __t.u32(),
  gems: __t.u32(),
});
export type PublicLeaderboardRow = __Infer<typeof PublicLeaderboardRow>;

export const PublicLiveDiscovery = __t.object("PublicLiveDiscovery", {});
export type PublicLiveDiscovery = __Infer<typeof PublicLiveDiscovery>;

export const PublicLiveDiscoveryItem = __t.object("PublicLiveDiscoveryItem", {
  liveId: __t.string(),
  hostUserId: __t.option(__t.string()),
  hostUsername: __t.option(__t.string()),
  hostAvatarUrl: __t.option(__t.string()),
  title: __t.string(),
  viewerCount: __t.u32(),
});
export type PublicLiveDiscoveryItem = __Infer<typeof PublicLiveDiscoveryItem>;

export const PublicLiveDiscoveryRow = __t.object("PublicLiveDiscoveryRow", {
  liveId: __t.string(),
  hostUserId: __t.option(__t.string()),
  hostUsername: __t.option(__t.string()),
  hostAvatarUrl: __t.option(__t.string()),
  title: __t.string(),
  viewerCount: __t.u32(),
});
export type PublicLiveDiscoveryRow = __Infer<typeof PublicLiveDiscoveryRow>;

export const PublicProfileSummary = __t.object("PublicProfileSummary", {});
export type PublicProfileSummary = __Infer<typeof PublicProfileSummary>;

export const PublicProfileSummaryItem = __t.object("PublicProfileSummaryItem", {
  userId: __t.string(),
  username: __t.string(),
  avatarUrl: __t.string(),
  badge: __t.option(__t.string()),
  spotlightStatus: __t.option(__t.string()),
});
export type PublicProfileSummaryItem = __Infer<typeof PublicProfileSummaryItem>;

export const PublicProfileSummaryRow = __t.object("PublicProfileSummaryRow", {
  userId: __t.string(),
  username: __t.string(),
  avatarUrl: __t.string(),
  badge: __t.option(__t.string()),
  spotlightStatus: __t.option(__t.string()),
});
export type PublicProfileSummaryRow = __Infer<typeof PublicProfileSummaryRow>;

export const SocialUserItem = __t.object("SocialUserItem", {
  userId: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type SocialUserItem = __Infer<typeof SocialUserItem>;

export const ThreadSeedMessage = __t.object("ThreadSeedMessage", {
  id: __t.string(),
  ownerUserId: __t.string(),
  otherUserId: __t.string(),
  messages: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ThreadSeedMessage = __Infer<typeof ThreadSeedMessage>;

export const Track = __t.object("Track", {
  id: __t.string(),
  title: __t.string(),
  artistId: __t.option(__t.string()),
  artworkUrl: __t.option(__t.string()),
  durationSeconds: __t.u32(),
  audioUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Track = __Infer<typeof Track>;

export const UserProfileItem = __t.object("UserProfileItem", {
  userId: __t.string(),
  profile: __t.string(),
  updatedAt: __t.timestamp(),
});
export type UserProfileItem = __Infer<typeof UserProfileItem>;

export const VideoItem = __t.object("VideoItem", {
  id: __t.string(),
  item: __t.string(),
  updatedAt: __t.timestamp(),
});
export type VideoItem = __Infer<typeof VideoItem>;

