// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  vuluUserId: __t.string().primaryKey().name("vulu_user_id"),
  createdAt: __t.timestamp().name("created_at"),
  displayName: __t.string().name("display_name"),
  avatar: __t.option(__t.string()),
  isBanned: __t.bool().name("is_banned"),
  banStatus: __t.string().name("ban_status"),
  banReason: __t.option(__t.string()).name("ban_reason"),
});
