// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  vuluUserId: __t.string().name("vulu_user_id"),
  provider: __t.string(),
  issuer: __t.string(),
  subject: __t.string(),
  email: __t.option(__t.string()),
  emailVerified: __t.bool().name("email_verified"),
  lookupKey: __t.string().name("lookup_key"),
  createdAt: __t.timestamp().name("created_at"),
});
